### PR TITLE
bump to GHC 9.4.8

### PR DESCRIPTION
**Pull request by gev**

### CODE REVIEW

**Comment by gev** [comment]
I used GHC 9.2.8 before as well
When try to use GHC 9.4.8:

```
src/Ivory/Language/Coroutine.hs:138:28: error:
    • Could not deduce (IvoryCall
                          ('[] :-> r0)
                          ('Effects ('Returns ()) b ('Scope s0))
                          (Ivory ('Effects ('Returns ()) b ('Scope s0)) (Ref s10 a)))
        arising from a use of ‘call’
      from the context: IvoryArea a
        bound by the type signature for:
                   coroutine :: forall (a :: Area (*)).
                                IvoryArea a =>
                                String -> CoroutineBody a -> Coroutine a
        at src/Ivory/Language/Coroutine.hs:(131,1)-(134,27)
      The type variables ‘r0’, ‘s0’, ‘s10’ are ambiguous
      Relevant bindings include
        fromYield :: forall (s1 :: Ivory.Language.Scope.RefScope) s2.
                     (forall (b :: BreakEff).
                      Ivory ('Effects ('Returns ()) b ('Scope s2)) (Ref s1 a))
                     -> Ivory (ProcEffects s2 ()) ()
          (bound at src/Ivory/Language/Coroutine.hs:135:31)
        coroutine :: String -> CoroutineBody a -> Coroutine a
          (bound at src/Ivory/Language/Coroutine.hs:135:1)
      Potentially matching instance:
        instance IvoryVar r => IvoryCall ('[] :-> r) eff (Ivory eff r)
          -- Defined in ‘Ivory.Language.Proc’
    • In the second argument of ‘($)’, namely
        ‘call (proc yieldName $ body $ return ())’
      In the second argument of ‘($)’, namely
        ‘fromYield $ call (proc yieldName $ body $ return ())’
      In the expression:
        runIvory $ fromYield $ call (proc yieldName $ body $ return ())
    |
138 |     runIvory $ fromYield $ call (proc yieldName $ body $ return ())
    |                            ^^^^

src/Ivory/Language/Coroutine.hs:138:34: error:
    • Could not deduce (IvoryType r0) arising from a use of ‘proc’
      from the context: IvoryArea a
        bound by the type signature for:
                   coroutine :: forall (a :: Area (*)).
                                IvoryArea a =>
                                String -> CoroutineBody a -> Coroutine a
        at src/Ivory/Language/Coroutine.hs:(131,1)-(134,27)
      The type variable ‘r0’ is ambiguous
      Potentially matching instances:
        instance ANat n => IvoryType (Ix n)
          -- Defined in ‘Ivory.Language.Array’
        instance IvoryType IBool -- Defined in ‘Ivory.Language.IBool’
        ...plus four others
        ...plus 12 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘($)’, namely ‘proc yieldName’
      In the first argument of ‘call’, namely
        ‘(proc yieldName $ body $ return ())’
      In the second argument of ‘($)’, namely
        ‘call (proc yieldName $ body $ return ())’
    |
138 |     runIvory $ fromYield $ call (proc yieldName $ body $ return ())
    |                                  ^^^^
cabal: Failed to build ivory-0.1.0.10 (which is required by
ivory-tasty-0.1.0.0, exe:ivory-c-clang-test from ivory-examples-0.1.0.5 and
others).

```
PR avoid this error

**Comment by sorki** [comment]
Thank you! I've seen this one pop up but since 9.6.3 CI was passing I decided to just skip older GHCs.

**Comment by gev** [comment]
I still didn't use 9.6. Now will try

**Comment by gev** [comment]
Happy New Year!

**Comment by sorki** [comment]
> Happy New Year!

Happy New Year! :partying_face: :

**Pull request merged**
